version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000" # or whatever your backend uses
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:3000" # expose React app on default HTTP port
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
